### ISSUE TITLE
Suggestion: Allow optional disabling of uasort call 

### ISSUE THREAD

**Issue by scottcwilson** [lat9/options_stock_support#23]
When I comment out admin/products_options_stock.php line 682 

uasort ($pos_product_options, 'pos_product_options_sort');

the products are sorted by option name, which is much easier to read.  (See old vs new images below).

<img width="523" alt="old" src="https://cloud.githubusercontent.com/assets/4391638/15273026/882364de-1a5a-11e6-8090-38ab56781633.png">
<img width="513" alt="new" src="https://cloud.githubusercontent.com/assets/4391638/15273027/8b81b720-1a5a-11e6-8bdb-3c7f674bd323.png">

**Comment by lat9** [comment]
v2.1.5 will include a sort-order dropdown in both the main and view-all tools to enable sort by products model as well.

**Comment by scottcwilson** [comment]
Great!  My client thinks your script is far superior to Stock by Attributes - just looking for a few additional tweaks to provide even greater flexibility.

**Comment by scottcwilson** [comment]
Works nicely!  Closing issue.
