### ISSUE TITLE
4.1.1 /156/YOUR_ADMIN\includes\functions\general.php has unrelated merges

### ISSUE THREAD

**Issue by torvista** [lat9/options_stock_support#24]
When compared to the vanilla 156 file, there are several changes in the POSM file from other mods that are not related to POSM. Also one change to add a space in a selector that is unclear if it is part of the POSM merge.

**Comment by lat9** [comment]
That's what I get, having a soup-to-nuts installation.  I'll get those changes backed out for the POSM distribution.

**Comment by lat9** [comment]
v4.1.2 has just been released, containing correction for this issue.
