### ISSUE TITLE
\zc156\ADMIN\category_product_listing.php not based on 156c file

### ISSUE THREAD

**Issue by torvista** [lat9/options_stock_support#25]
There are a lot of differences between the 156c file and the POSM file not related to POSM: I don't think it is based on the 156c file so is difficult to compare/merge.

Same thing for the catalog functions_lookups.php

**Comment by lat9** [comment]
You're correct, it's not.  Per the documentation, that's the (unsuffixed) zc156 version of the file, to be used on (unsuffixed) zc156 installations only.

**Comment by torvista** [comment]
Ah, documentation. RTFM. understood!
