### ISSUE TITLE
Product variant inserted via dbio does not use default sort order for the option value

### ISSUE THREAD

**Issue by RixStix** [lat9/options_stock_support#29]
dbio.OptionsStockFull.xxxxx has no field for sort order, so my assumption was that the option value would use its default sort order.  Instead all inserts are sort order zero which requires a manual visit to each attribute option and manually adjust the option value sort order

**Comment by lat9** [comment]
I don't understand the issue.  The `OptionsStockFull` handler affects only the `products_options_stock` and `products_options_stock_attributes` tables, neither of which has a `sort_order` field.

**Comment by RixStix** [comment]
I thought the handler was used to add/insert option values to a product.  I must have misread the docs.
It did add the option value as expected but with a sort order of zero.

Which handler should be used to add option values to existing product and use the option value default sort order?  I guess this is more a dbio understanding than a POSM understanding.

**Comment by lat9** [comment]
Whoops, I misspoke.  That handler *is* adding the options if they're not present.

Let me check.

**Comment by lat9** [comment]
I'm closing in on this change, but have a couple of clarifications needed.

I'm not sure whether you're referring to the sort-order of an added `option_value` or the sort-order of an added `attribute` (or both).  

For the `option_value` sort, I'm planning to assign any newly-added option-value's sort-order as the maximum sort (**+ 5**) of all option-values currently associated with the specified `option_id`.  That will provide some 'spacing' between those option-value sorts and make it a bit easier to go back and re-arrange if needed.  

For the `attribute` sort, I'm planning to assign any newly-added product-attribute's sort-order as the maximum sort (**+ 5**) of all attributes for the given product/option combination.

Let me know if this is going to 'work for you'.

**Comment by RixStix** [comment]
Maybe I am lost on the other side of the forest and speaking a different language.  

I was attempting to insert an existing option_value to an existing product and expected the default sort-order of the option_value to be used instead of zero or a newly created sort-order.  Both cause the newly inserted option_value to be out of order.  These option_values, when initially added to the database, were assigned default sort-orders so that they would always fall into the proper order in the list when used.

I was not attempting to create/add a new option_value.

Example being an option_value of 16.00 mm being added to to a product and the default sort-order of that option-value is 1600.  The would cause the option_value to fall into the proper place in the list of 24+ option-values already associated with the product.  When I imported the csv, the default option_value was set to zero instead of using 1600

**Comment by lat9** [comment]
Perhaps ...

Is this the sort-order present in the `products_attributes` table?  If so, then the sort-order of that added attribute should (??) be set to the sort-order associated with that newly-added option-value?

**Comment by RixStix** [comment]
Yes, the sort-order present in the products_attributes table, but it wasn't set to that value.  It was blank or zero.

If it wasn't, but should have been, then maybe it was a "Me" issue.

**Comment by lat9** [comment]
v4.1.5 was just released, containing the change associated with this issue.  Anyone who's signed up for notifications on _POSM_ changes has been notified.
