### ISSUE TITLE
console error on Add to Cart with no selection made

### ISSUE THREAD

**Issue by torvista** [lat9/options_stock_support#31]
Radio buttons, no default.
Click on Add to Cart with no selection made:

![Clipboard01](https://user-images.githubusercontent.com/4391026/85368216-2360f780-b52b-11ea-8e97-d1891ae26ae1.gif)

**Comment by lat9** [comment]
Hmm, I'm not seeing that.  I modified the "Bugs Life" demo product to include only the Color options, identifying no default.  When I click the add-to-cart button without choosing a color, I see

![image](https://user-images.githubusercontent.com/2685585/85403900-21e3ff00-b52c-11ea-8861-b4b6d3f5e4b7.png)

How is your product set up? Which version of POSM?

**Comment by torvista** [comment]
It's the latest POSM.
The product has two options. The price is the base price/not priced by attributes.
The real web is the shown address minus the .local bit, if you want to look at it. I switched to the full-fat version.
I note the error description is different in Chrome and Firefox.

**Comment by lat9** [comment]
Hmm, that's because your customizations have removed the `.optionName` element (**Color** in the screenshot posted above).  

Let me see what the POSM dependencies jQuery can do to work with this.

**Comment by lat9** [comment]
I've got the correction for this issue staged for the forthcoming v4.1.6 release of POSM.

**Comment by lat9** [comment]
Correction has been provided in v4.1.6; please validate and close if you agree that the issue's corrected.

**Comment by torvista** [comment]
yes
