### ISSUE TITLE
Request: display of model number product selection, shopping cart

### ISSUE THREAD

**Issue by torvista** [lat9/options_stock_support#34]
1) Product Selection
I would like to be able to include the model number with the option, as marked by the arrow.

![product selection](https://user-images.githubusercontent.com/4391026/89729843-b6051980-da39-11ea-8856-bc38e652dccc.gif)

2) In the cart, the option to use the model number is available, but it is appended to the product name.
![cart std](https://user-images.githubusercontent.com/4391026/89729958-a2a67e00-da3a-11ea-842b-6c4194da70c3.gif)

I have that switched off, and made a modification to add it to the attribute, which seems more logical to me:

![cart](https://user-images.githubusercontent.com/4391026/89729891-30ce3480-da3a-11ea-8abe-33e2ac6e5ffa.gif)

**Comment by lat9** [comment]
That'll work for products with a _single_ managed option.  How would you envision this feature 'displaying' for products with multiple (e.g. Size and Color) options?

Would this change also affect the display in the checkout-confirmation, checkout-confirmation email, checkout-success and account-history-info renderings?  What about in the admin's orders/edit-orders/invoice/packingslip displays?

**Comment by torvista** [comment]
Unsurprisingly you are right

**Comment by lat9** [comment]
Just coming back ... what if the model number was displayed on the final option-combination?

**Comment by torvista** [comment]
![Clipboard01](https://user-images.githubusercontent.com/4391026/90287086-71351480-de77-11ea-9986-3c7f57e0a1ed.gif)

I think this is default, it's fine!
