### ISSUE TITLE
Admin, POS manager: option sort order

### ISSUE THREAD

**Issue by torvista** [lat9/options_stock_support#35]
1) 
![Clipboard01](https://user-images.githubusercontent.com/4391026/90282555-d9cbc380-de6e-11ea-9526-5b672d5dd742.gif)
On changing this dropdown, the current product is not reselected. I think the pid is not being carried over.

2) Despite all options on this product have a sort order of 1, 

![Clipboard02](https://user-images.githubusercontent.com/4391026/90282814-52cb1b00-de6f-11ea-94d7-14390217ced6.gif)

they are not alpha sorted, as described in the previous text description.

![Clipboard03](https://user-images.githubusercontent.com/4391026/90282911-78f0bb00-de6f-11ea-86e0-964f3b7ae185.gif)

**Comment by lat9** [comment]
Thanks for the report; I've got it under investigation.
