### ISSUE TITLE
Documentation, admin POS manager: Insert options Add or Replace Stock

### ISSUE THREAD

**Issue by torvista** [lat9/options_stock_support#36]
I don't find an explanation for these radio buttons in the docs/am not clear on the function.
Is this just a one-time thing on the initial insert?

**Comment by lat9** [comment]
Documentation updated: https://github.com/lat9/options_stock_support/blob/master/pages/admin_interfaces.md#catalog-manage-options-stock

Let me know if I need to fill in any additional 'blanks'.

**Comment by torvista** [comment]
I had no idea that that line could be used for stock updates, I thought it was only for adding new options! Hence I was failing to understand add/replace in that context!
