### ISSUE TITLE
DBIO Handler optionsStockUpdate: bulk removal of options stock combinations?

### ISSUE THREAD

**Issue by torvista** [lat9/options_stock_support#37]
I have a series of products, each with colour options that I would like to remove with an import.
Is it possible to bulk remove products option-stock records, or only update?

**Comment by lat9** [comment]
The [`DbIoOptionsStockFullHandler`](https://github.com/lat9/options_stock_support/blob/master/pages/dbio.md) supports the `REMOVE` command, so you can bulk-remove!

**Comment by torvista** [comment]
Yes, with FullHandler, I was using update.
