### ISSUE TITLE
Integration with Global Tools (Option Names and Values Manager)

### ISSUE THREAD

**Issue by torvista** [lat9/options_stock_support#38]
Currently the deletion of an attributes in Attribute Controller also deletes the corresponding POSM entry.
I note the Option name Manager Global Tool "Delete all Option Values from ONE Category of products for this Option Name" does not auto-delete the POSM entries.
There are a lot of tools in Names and Values Manager and **I** would not want to integrate all of them with POSM, but a comment / a documentation entry would be of interest, to clarify your position.

**Comment by lat9** [comment]
Nor I!  I'll get a documentation update going, perhaps with some kind of admin-message for the condition to remind users.

**Comment by lat9** [comment]
This issue will be addressed in the upcoming v4.3.1 release.
