### ISSUE TITLE
Incorrect reporting of duplicate

### ISSUE THREAD

**Issue by torvista** [lat9/options_stock_support#39]
Admin, Check for Duplicates is spitting out some things...for example
![duplicate](https://user-images.githubusercontent.com/4391026/94859328-a4862f80-0434-11eb-894b-1aa0b1ecf070.gif)

See the base model is HT-BLP...not used anywhere else.

Clicking on the link opens the posm admin screen...but despite the pid being passed with the url, no product or category is selected.

After selecting the offending product, the posm SKUs are distinct.
So, don't know why this is a duplicate.

![POSM](https://user-images.githubusercontent.com/4391026/94859513-ef07ac00-0434-11eb-93cd-3777fa8df86c.gif)

**Comment by lat9** [comment]
This bug will be addressed in POSM v4.2.2.
