### ISSUE TITLE
Removal of Orphan POSM entries 

### ISSUE THREAD

**Issue by torvista** [lat9/options_stock_support#40]
I have cases of POSM entries (Blue square in product listing), where the attributes have been deleted....but not the POSM entries. But on entering PSOM admin, nothing is shown for that product id.

This has happened I think due to
a) in the early POSM days when the POSM entry was not auto-deleted when the attribute was deleted in Attribute Manager.
b) use of global tools in Values manager that have no POSM integration.

So, is this just a matter of deleting the entries for that product id in the products_options_stock_table **only**?

Could you come up with a sql query to find and delete these orphans?
Thanks.

**Comment by lat9** [comment]
Sure:
```
SELECT posa.products_id, posa.options_id, posa.options_values_id
  FROM products_options_stock_attributes posa
 WHERE NOT EXISTS (
          SELECT pa.products_id, pa.options_id, pa.options_values_id
            FROM products_attributes pa
           WHERE pa.products_id = posa.products_id
             AND pa.options_id = posa.options_id
             AND pa.options_values_id = posa.options_values_id
       )
 ORDER BY posa.products_id, posa.options_id, posa.options_values_id
```
I'll see about using this in a to-be-created tool to help in the management of those entries.
