### ISSUE TITLE
Handling EAN  European Article Number

### ISSUE THREAD

**Issue by torvista** [lat9/options_stock_support#41]
Google Merchant Center complains that some products should have a GTIN so I am adding EAN to the products table, which will serve for simple products.
Now, how would this best be handled for attributes' EAN, to not imply a change to POSM?

This data/GTIN would be output by a structured data plugin, which would check for a POSM product then get POSM model and lookup if-exists EAN in a new table? Or have the whole lot in a new table of Model->EAN equivalences?

**Comment by lat9** [comment]
I'd created an extension to _POSM_ a couple of years ago (not released) that adds a GTIN/MPN setting for each managed option.

It needs some basic care-and-feeding to make it releasable and I've put it on my ever-expanding to-do list.

**Comment by torvista** [comment]
While my needs are relatively simple regarding the narrow range of products we sell, it looks like there is a need for a broader solution for additional product data in light of overlapping/or not Google Merchant Centre (GMC)/Structured Data (SD) requirements.
Like
sku (GMC/SD) - shop-specific reference, which would be the current products_model. 
mpn (GMC/SD) - manufacturers part number
gtin (GMC/SD) - international number
google_products_category (GMC) - a google-defined product category. Handily, this can be a number from their spreadsheet. https://support.google.com/merchants/answer/6324436?hl=en-GB

So, after just trying to correct a few feed errors, a world of pain emerges with what looks like a need for a core extension, with hooks for POSM....maybe to be discussed elsewhere with a budget!!

**Comment by torvista** [comment]
In the end I am just adding three fields to the product table, with no admin access as all of these only have to be input once.
The only doubt is where to put two datas (mpn, gtin) data for POSM products?

**Comment by torvista** [comment]
I've put extra fields pos_mpn, pos_ean in products_options_stock.

I concluded that gtin is an outside-world facing thing, which can be loaded with various codes depending on the product/shop inquestion so it was not apprpriate to use a db field named as gtin as it does not reflect the real content of the field, only it's use.

So, I decided that the database column should reflect the content, which in my case will be ean.

I've just added code to output all this to my Structured Data plugin, as part of an update for attributes, which will be available shortly...

**Comment by torvista** [comment]
After moving my product extra fields, admin input fields from hard-coded to an observer, I am considering what to do about the same fields for POSM products. 
I have them in the database in extra fields in  products_options_stock, since variants have different EAN and MPN.
But as to the best approach for adding input fields to the POSM manager, either it needs notifiers so the plugin has a plugin, or hard-coded mods (no) or the add-on you mentioned, or include this capability in the plugin but with user-defined column names....
Thoughts?
