### ISSUE TITLE
Some POSM handling on product info page still occurs when module disabled

### ISSUE THREAD

**Issue by torvista** [lat9/options_stock_support#45]
After a good while bouncing between different ZC versions to try and figure out why only one of three equally-configured attributes could be added to the cart, I found that the permitted attribute was the only one with a POSM model number assigned, despite the module being disabled. Deletion of the POSM entry restored normal service.
I expected that with the module disabled, no handling would occur at all, to help troubleshooting an unrelated issue.

**Comment by lat9** [comment]
Thanks for the report, I'll investigate over the next week.
