### ISSUE TITLE
Admin, options stock SKU field size: admin setting always overrides inline field size

### ISSUE THREAD

**Issue by torvista** [lat9/options_stock_support#47]
I note that an admin configuration constant defines the field size as a css value.
`input[type="text"].model-num { width: <?php echo POSM_ADMIN_MODEL_WIDTH; ?>; font-family: "Courier New", Courier, monospace; font-size: 12px; }`

So the code for setting the size calculated from the table field size is always overridden/redundant.
`$model_field_size = zen_set_field_length(TABLE_PRODUCTS_OPTIONS_STOCK, 'pos_model');` 

` <td class="dataTableContent centered"><?php echo zen_draw_input_field("pos_model[$pos_id]", $pos_model, 'class="model-num' . $extra_model_class . '" ' . $model_field_size . '"'); ?></td>`

I would suggest the admin switch be labelled as an override and provision made it for to be empty.

**Comment by lat9** [comment]
I agree with your suggestion; it'll be included in the next version of POSM.

**Comment by lat9** [comment]
Updated with v4.3.0.
