### ISSUE TITLE
Notifier not working: No update() method (or matching alternative) found 

### ISSUE THREAD

**Issue by torvista** [lat9/options_stock_support#49]
While adding extra fields to the products_options_stock page, I've added a couple of notifiers to keep the originals intact for easier future comparisons, they are working.

But I found that this:
POSM_UPDATE_DATABASE_RECORD2 
would not fire unless renamed as
NOTIFY_POSM_UPDATE_DATABASE_RECORD2.

It gives this error (using an auto-loading observer, ZC158, php 7.3/8.08)
--> PHP Warning: WARNING: No update() method (or matching alternative) found in the zcObserverPluginExtraPosmFields class for event POSM_UPDATE_DATABASE_RECORD2 in .....includes\classes\traits\NotifierManager.php on line 93.

**Comment by lat9** [comment]
Well, isn't zc158 a bit of a PITA?  I'll review the notifications issued and make sure that they're aligned with this new/future Zen Cart requirement.

**Comment by lat9** [comment]
I'll note that this change in behavior affects any observers that make use of the _camelCased_ version of the notification's update.  zc158 has changed the rules so that a notification must be prefixed with `NOTIFY_` for the observer's update method to 'bind' to the notification.
